### PR TITLE
Fix double-counting of 1-4 pairs in rings

### LINKED ISSUE #224: Found bug in gromacs top writer
When working on debugging #182, I found a bug in the internal gromacs writer. Short summary: when writing out the `top` file, we realize some entries in the `pairs` section are duplicated 

Code to reproduce the issue 
```
benzene = Molecule.from_file('openffsystem/openff/system/tests/files/foyer_test_molecules/benzene.sdf')
off_bio_top = OFFBioTop.from_molecules(benzene)
off_bio_top.mdtop = md.Topology.from_openmm(off_bio_top.to_openmm())
oplsaa = foyer.Forcefield(name='oplsaa')
off_system = from_foyer(off_bio_top, oplsaa)

off_system.positions = benzene.conformers[0].value_in_unit(omm_unit.nanometer)

off_system.box = [4, 4, 4]
off_system.to_top('benzene.top')
```
Output: the pair 1-4 and 3-6 got repeated twice. 
Screen Shot 2021-06-17 at 17 25 26

### PR DESCRIPTION
**Pull request by mattwthompson**
### Description
Fixes #224 

### Checklist
- [x] Add tests
- [x] Lint
- [ ] Update docstrings

### CODE REVIEW

**Comment by mattwthompson** [comment]
@daico007 please let me know if this fixes your test case!

**Review by daico007 — APPROVED** [review]
Thanks @mattwthompson! These changes fix the energy difference in my benzene example.

**Review by justinGilmer — APPROVED** [review]
LGTM!

**Comment by mattwthompson** [comment]
Thanks!

**Pull request merged**
