### PR TITLE
Fix CI

### PR DESCRIPTION
**Pull request by mattwthompson**

### CODE REVIEW

**Comment by mattwthompson** [comment]
Nothing is failing locally and I've updated my environment to match the file `test_env.yaml` tracked here.

Exit code 134 coming from a SIGABRT implies too much memory is being used. I used a [`pytest-monitor`](https://pytest-monitor.readthedocs.io/en/latest/operating.html) to see how much is being used locally and it tops out around 250 MB. This is higher than I'd prefer but well under the 2 GB limit that I think we're provided with these runners.

**Comment by mattwthompson** [comment]
Here's the diff between envs that are failing and passing; deps on `>` lines or some interaction with them are causing the segfault. Again, this is not happening locally so it's tedious to debug.


```shell
1c1
< name: openff-interchange-minimal-env
---
> name: openff-interchange-env
3a4,5
>   - bioconda
>   - openeye
14a17,21
>   # Optional features
>   - jax
>   - unyt
>   - mbuild
>   - foyer >=0.8.1
15a23,27
>   - mdtraj
>   - intermol
>   - openff-evaluator
>   - openff-recharge
>   - openeye-toolkits
16a29,30
>   - codecov
>   - pytest-cov
17a32,34
>   - pytest-randomly
>   - pytest-timeout
>   - nbval
18a36,49
>   - nglview
>   # Drivers
>   - gromacs >=2021
>   - lammps
>   - panedr
>   # Typing
>   - mypy
>   - typing-extensions
>   - types-setuptools
>   - types-pkg_resources
>   - pandas-stubs
>   - openff-evaluator
>   - openff-recharge
>   - openeye-toolkits
21d51
<   - mdtraj

**Comment by mattwthompson** [comment]
The problem is likely https://github.com/conda-forge/jaxlib-feedstock/issues/89; I don't have the bandwidth to fix it so I have to pin around it.

**Comment by mattwthompson** [comment]
Still kinda broken; may have to `pip install jax` if the issue persists

**Comment by mattwthompson** [comment]
Docs still broken but I've already spent too much time getting CI passing

**Comment by xhochy** [comment]
@mattwthompson We've fixed the `jaxlib` issue and you should be able to revert this PR.

**Comment by mattwthompson** [comment]
Thanks!

**Pull request merged**
