### PR TITLE
Document that topology charges are ignored

### LINKED ISSUE #1058: `charge_from_molecules` silently ignores isomorphic molecules in list, only using the first entry
**Description**

Passing two isomorphic Molecules with different partial charges to `from_smirnoff`'s `charge_from_molecules` flag will lead to partial charges only being assigned from the first Molecule.

**Reproduction**

```python
from openff.toolkit import Molecule, Topology, ForceField
from openff.interchange.components._packmol import solvate_topology_nonwater
from openff.interchange import Interchange
import pytest

solvent = Molecule.from_smiles('c1ccccc1')
solvent.assign_partial_charges(partial_charge_method='gasteiger')
print("solvent charges: ", solvent.partial_charges)

ligand = Molecule.from_smiles('c1ccccc1')
ligand.generate_conformers()
ligand.assign_partial_charges(partial_charge_method='am1bcc')
print("ligand charges: ", ligand.partial_charges)

print("molecules are isomorphic: ", ligand.is_isomorphic_with(solvent))

off_top = Topology.from_molecules(ligand)
solvated_off_top = solvate_topology_nonwater(topology=off_top, solvent=solvent)

ff = ForceField('openff-2.2.0.offxml', 'opc.offxml')
inter = Interchange.from_smirnoff(topology=solvated_off_top, force_field=ff, charge_from_molecules=[ligand, solvent])

for _, c in inter.collections["Electrostatics"].charges.items():
    assert abs(c.m) == pytest.approx(0.13)
    
inter = Interchange.from_smirnoff(topology=solvated_off_top, force_field=ff, charge_from_molecules=[solvent, ligand])

for _, c in inter.collections["Electrostatics"].charges.items():
    assert abs(c.m) == pytest.approx(0.06226857)
```

**Output**

```
solvent charges:  [-0.062268570782092456 -0.062268570782092456 -0.062268570782092456 -0.062268570782092456 -0.062268570782092456 -0.062268570782092456 0.062268570782092456 0.062268570782092456 0.062268570782092456 0.062268570782092456 0.062268570782092456 0.062268570782092456] elementary_charge
ligand charges:  [-0.13 -0.13 -0.13 -0.13 -0.13 -0.13 0.13 0.13 0.13 0.13 0.13 0.13] elementary_charge
molecules are isomorphic:  True
```

**Software versions**

Interchange v0.3.29

### LINKED ISSUE #1059: `from_smirnoff` _without_ `charge_from_molecules` silently assigns all isormophic molecules the same partial charges
**Description**

User case:

I construct an Interchange object from a Topology with two or more ismorphic Molecules with different partial charges.
In this case the first Molecule has am1bcc charges whilst all the others have gasteiger charges, which differ significantly.

Outcome: 

All the Molecules silently get assigned the partial charges from the first Molecule.

**Reproduction**

```python
from openff.units.openmm import from_openmm
from openmm import NonbondedForce
from openff.toolkit import Molecule, Topology, ForceField
from openff.interchange.components._packmol import solvate_topology_nonwater
from openff.interchange import Interchange
import pytest

solvent = Molecule.from_smiles('c1ccccc1')
solvent.assign_partial_charges(partial_charge_method='gasteiger')
print("solvent charges: ", solvent.partial_charges)

ligand = Molecule.from_smiles('c1ccccc1')
ligand.generate_conformers()
ligand.assign_partial_charges(partial_charge_method='am1bcc')
print("ligand charges: ", ligand.partial_charges)

print("molecules are isomorphic: ", ligand.is_isomorphic_with(solvent))

off_top = Topology.from_molecules(ligand)
solvated_off_top = solvate_topology_nonwater(topology=off_top, solvent=solvent)

ff = ForceField('openff-2.2.0.offxml', 'opc.offxml')
inter = Interchange.from_smirnoff(topology=solvated_off_top, force_field=ff)

for _, c in inter.collections["Electrostatics"].charges.items():
    assert abs(c.m) == pytest.approx(0.13)
    
# Double check this isn't just the collection, and it goes all the way to an openmm System
system = inter.to_openmm_system()
nonbond = [f for f in system.getForces() if isinstance(f, NonbondedForce)][0]

for idx in range(system.getNumParticles()):
    c, _, _ = nonbond.getParticleParameters(idx)
    assert abs(from_openmm(c).m) == 0.13

print(all(solvated_off_top.molecule(0).partial_charges == ligand.partial_charges))
print(all(solvated_off_top.molecule(1).partial_charges == ligand.partial_charges))
print(all(solvated_off_top.molecule(1).partial_charges == solvent.partial_charges))
```

**Output**

```
solvent charges:  [-0.062268570782092456 -0.062268570782092456 -0.062268570782092456 -0.062268570782092456 -0.062268570782092456 -0.062268570782092456 0.062268570782092456 0.062268570782092456 0.062268570782092456 0.062268570782092456 0.062268570782092456 0.062268570782092456] elementary_charge
ligand charges:  [-0.13 -0.13 -0.13 -0.13 -0.13 -0.13 0.13 0.13 0.13 0.13 0.13 0.13] elementary_charge
molecules are isomorphic:  True
True
False
True
```

**Software versions**

Interchange v0.3.29

### PR DESCRIPTION
**Pull request by mattwthompson**
### Description

Resolves #1059

### Checklist

- [x] Document details relevant to #1059

### CODE REVIEW

**Comment by davidlmobley** [comment]
I read the updated doc strings, and I'm not sure the changes make the implications sufficiently clear for a use case like Irfan's. Should it explicitly say somewhere that in no case can isomorphic molecules end up with different charge sets?

**Review by IAlibay — COMMENTED** [review]
@mattwthompson this seems to address #1059 but not #1058 is this intended?

**Comment by mattwthompson** [comment]
Whoops, yes, this is meant to address #1059!

**Comment by mattwthompson** [comment]
> Should it explicitly say somewhere that in no case can isomorphic molecules end up with different charge sets?

Separate issue (due to my mistake) but in #1070 I'm adding an error when `charge_from_molecules` includes any isomorphic molecules

**Pull request merged**
