### PR TITLE
fix issue with python 3.10

### PR DESCRIPTION
**Pull request by mikemhenry**
### Description
You will need to quote the python version when you add python 3.10 eventually

### Checklist
- [ ] Add tests
- [ ] Lint
- [ ] Update docstrings

### CODE REVIEW

**Review by mattwthompson — APPROVED** [review]
LGTM - I think I saw something about this a few months ago when it was released, but have yet to be burnt by it so I didn't change anything.

**Comment by mikemhenry** [comment]
Yah at first I tried just adding quotes in the list, but needed it where it defined the python version in the yml and still failed, I caught it when I used your GHA yml as inspiration for another repo

**Comment by mattwthompson** [comment]
Yeah, It'll be a while until our stack is compatible with 3.10 - though you're closer to the tap with OpenMM being of the current blockers.

**Comment by mikemhenry** [comment]
:see_no_evil:

**Pull request merged**
