### PR TITLE
Foyer tests

### PR DESCRIPTION
**Pull request by umesh-timalsina**
### Description
Add tests for foyer parameterized systems added in #114. Depends on #166.

### Some discussion points/comments on the PR.
- Setting gen-pairs to yes in the gmx topfile for OPLSAA Force Field is not necessary or might lead to energy differences.

- We currently have differences in the output top files specifically the default section

OpenFF-Defaults (ethanol system)
[ethanol_openff.txt](https://github.com/openforcefield/openff-system/files/6469374/ethanol_openff.txt)

Parmed Defaults (parameterized ethanol)
[ethanol.txt](https://github.com/openforcefield/openff-system/files/6469370/ethanol.txt)

- Largest energy differences were found for “Angles” and “Electrostatics”.

### CODE REVIEW

**Comment by justinGilmer** [comment]
I’ll note here as well that the two files listed above are a concatenation of their respective gro and top files.

**Comment by mattwthompson** [comment]
Thanks for getting this started!

Could you document how the test files were generated? See https://github.com/openforcefield/openff-system/blob/master/openff/system/tests/files/README.md for what I have been trying to do so far.

> Setting gen-pairs to yes in the gmx topfile for OPLSAA Force Field is not necessary or might lead to energy differences.

It probably doesn't when written by ParmEd, since it defines the parameters of each pair, overriding the `fudgeLJ` up top. That's how it can be the totally-wrong value of 1 and work. The approach I have implemented right now, which can change if needed, is to define the atom indices of each pair and letting GROMACS compute the parameters according to `fudgeLJ` (which matters in this case).

> We currently have differences in the output top files specifically the default section

The combination rule is not specified at the moment. This will soon be hard-coded as a required field into the vdW handlers (#178).

> Largest energy differences were found for “Angles” and “Electrostatics”.

Spot-checking the files side-by-side, the `[ angles ]` section and charges seem identical. This leads me to think the energy differences are due to how things are defined. There's a temporary file `auto_generated.mdp` that's written out that specifies the details of the MM calculation. There might be some differences (cutoffs, etc.) there. I

**Comment by mattwthompson** [comment]
@umesh-timalsina @justinGilmer @daico007 I have tried to merge some huge upstream changes (#217) into this branch, and also merged in a smaller change (#214). I'm able to start tests locally, so I think I did it reasonably well, but it may require some care on your part to ensure I didn't make any unwanted changes.

**Comment by mattwthompson** [comment]
@daico007 @justinGilmer @umesh-timalsina I'm still getting some large energy differences - larger than what you shared last week. Is there work you've done that hasn't been committed?

**Comment by daico007** [comment]
@mattwthompson as of right now, we still can't specify the decimal of the `.gro` file through the `get_gromacs_energy`, which cause the huge difference in bond/angles/RB potential. We will work on a PR to add a **kwargs to the `get_gromacs_energy` function.

**Comment by daico007** [comment]
This PR now is depending on #237

**Comment by mattwthompson** [comment]
I can isolate the issue to 1-4 interactions, but absolutely nothing I've been able to dig into has appeared to be out of place.

I stripped down one of the unit tests to this script


```python3
import foyer
import mdtraj as md
import parmed as pmd
from openff.toolkit.topology.molecule import Molecule
from openff.units import unit
from simtk import unit as omm_unit

from openff.interchange.components.interchange import Interchange
from openff.interchange.components.mdtraj import OFFBioTop
from openff.interchange.drivers.gromacs import _get_mdp_file, _run_gmx_energy
from openff.interchange.utils import get_test_file_path

kj_mol = unit.Unit("kilojoule / mol")

oplsaa = foyer.forcefields.load_OPLSAA()

molecule_path = get_test_file_path("foyer_test_molecules/benzene.sdf")
molecule = Molecule.from_file(molecule_path)
molecule.name = "BENZ"


top = OFFBioTop.from_molecules(molecule)
top.mdtop = md.Topology.from_openmm(top.to_openmm())
openff_interchange = Interchange.from_foyer(top, oplsaa)

openff_interchange.positions = molecule.conformers[0].value_in_unit(omm_unit.nanometer)
openff_interchange.box = [4, 4, 4]

struct_no_data = pmd.openmm.load_topology(top.to_openmm())
struct_no_data.positions = openff_interchange.positions.m_as(unit.angstrom)
struct_no_data.box = [40, 40, 40, 90, 90, 90]

struct = oplsaa.apply(struct_no_data)

# openff_energy = get_gromacs_energies(
#     openff_interchange, decimal=3, mdp="cutoff_hbonds"
# )
openff_interchange.to_gro("openff.gro", writer="internal", decimal=3)
openff_interchange.to_top("openff.top", writer="internal")

struct.combining_rule = "geometric"
struct.save("foyer.gro", overwrite=True)
struct.save("foyer.top", overwrite=True)

through_foyer = _run_gmx_energy(
    top_file="foyer.top",
    gro_file="foyer.gro",
    mdp_file=_get_mdp_file("cutoff_hbonds"),
)

through_openff = _run_gmx_energy(
    top_file="openff.top",
    gro_file="openff.gro",
    mdp_file=_get_mdp_file("cutoff_hbonds"),
)

through_openff.compare(
    through_foyer,
    custom_tolerances={
        #     "Bond": 1e-3 * unit.kilojoule / unit.mole,
        #     "Angle": 1e-3 * unit.kilojoule / unit.mole,
        #     "Nonbonded": 1e-3 * unit.kilojoule / unit.mole,
        #     "Torsion": 1e-3 * unit.kilojoule / unit.mole,
        "vdW": 2e-2 * unit.kilojoule / unit.mole,
        #     "Electrostatics": 1e-3 * unit.kilojoule / unit.mole,
    },
)

```

and also added this tiny patch for debugging raw `gmx energy` outputs:

```git
diff --git a/openff/interchange/drivers/gromacs.py b/openff/interchange/drivers/gromacs.py
index aff1247..7d34c28 100644
--- a/openff/interchange/drivers/gromacs.py
+++ b/openff/interchange/drivers/gromacs.py
@@ -277,7 +277,8 @@ def _parse_gmx_energy(edr_path: str) -> EnergyReport:
     energies_dict: Dict = df.to_dict("index")  # type: ignore[assignment]
     energies = energies_dict[0.0]
     energies.pop("Time")
-
+    import pprint
+    pprint.pprint(energies)
     for key in energies:
         energies[key] *= kj_mol
```

Some parsing of STDOUT basically tells me the following differences:

```
Coulomb-14 1.430511474609375e-06
LJ-14 -0.018924713134765625
```

All other components of the potential energy function are matching to **16 significant figures**.

I'm willing to ignore the electrostatics at that order of magnitude. The LJ interactions still stump me as much as they stumped us yesterday. Some of the things I've tried:
* Double-checking what ParmEd computes the sigma and scaled epsilon values to be (all seem accurate)
* Manually changing the mixing rule to Lorentz-Berthelot (differences with different values on the same order of magnitude)
* Manually inspect the gro files (character-for-charter identical within how GROMACS parses it)
* Manually checking the atom indices in the `[ pairs ]` section of each file (everything is identical)

At the point the only thing I can think of is changing the behavior of `to_top` to do what ParmEd does: `gen-pairs` set to `no` and manually compute the sigma and epsilon of each pair.

**Comment by mattwthompson** [comment]
Here are the files produced: [foyer.tar.gz](https://github.com/openforcefield/openff-interchange/files/6717690/foyer.tar.gz)

**Review by mattwthompson — APPROVED** [review]
I think it's best to merge this now and work on the related fix after https://github.com/mosdef-hub/foyer/issues/431 is resolved

**Pull request merged**
